# =====================================================
# Azure OpenAI 配置示例 - GPT-4o
# 适用于: Magentic-UI + Azure OpenAI 服务
# =====================================================

######################################
# 核心模型配置 - Azure OpenAI         #
######################################
model_config: &client
  provider: AzureOpenAIChatCompletionClient
  config:
    model: gpt-4o
    azure_endpoint: $AZURE_ENDPOINT
    azure_deployment: $AZURE_DEPLOYMENT
    api_version: "2024-10-21"
    timeout: 120.0
    max_retries: 3
    azure_ad_token_provider:
      provider: autogen_ext.auth.azure.AzureTokenProvider
      config:
        provider_kind: DefaultAzureCredential
        scopes:
          - https://cognitiveservices.azure.com/.default
    model_info:
      vision: true
      function_calling: true
      json_output: true
      family: gpt-4o
      structured_output: true
      multiple_system_messages: false
    extra_body:
      temperature: 0.7
      max_tokens: 4096
      top_p: 0.9

######################################
# 各代理专用配置                      #
######################################

orchestrator_client: *client
coder_client: *client
web_surfer_client: *client
file_surfer_client: *client

# 动作守卫使用更快的模型
action_guard_client:
  provider: AzureOpenAIChatCompletionClient
  config:
    model: gpt-4o-mini
    azure_endpoint: $AZURE_ENDPOINT
    azure_deployment: $AZURE_DEPLOYMENT_MINI  # 不同的部署名
    api_version: "2024-10-21"
    timeout: 60.0
    max_retries: 2
    azure_ad_token_provider:
      provider: autogen_ext.auth.azure.AzureTokenProvider
      config:
        provider_kind: DefaultAzureCredential
        scopes:
          - https://cognitiveservices.azure.com/.default
    model_info:
      vision: false
      function_calling: true
      json_output: true
      family: gpt-4o-mini
      structured_output: true
    extra_body:
      temperature: 0.3
      max_tokens: 2048

######################################
# 应用程序配置                        #
######################################

cooperative_planning: true
autonomous_execution: false
allow_follow_up_input: true
max_actions_per_step: 8
multiple_tools_per_call: true
max_turns: 50
model_context_token_limit: 128000
approval_policy: auto-conservative
action_guard_enabled: true
require_authentication: false
allowed_websites: []
browser_headless: false
browser_local: false
playwright_port: -1
novnc_port: -1
inside_docker: true
run_without_docker: false
allow_for_replans: true
do_bing_search: false
websurfer_loop: false
retrieve_relevant_plans: never 